### ISSUE TITLE
Ruby 2.x compatability?

### ISSUE THREAD

**Issue by odigity** [gristmill/phaxio#10]
I saw this at the top of the README:

"Note: This gem only runs on Ruby version 1.9.+"

Is this still true?  What is the nature of the incompatibility, and do you know if it is going to get fixed soon?  I'd really like to use this gem, but we run Ruby 2.1.1.

**Comment by nerab** [comment]
I verified that this gem works with MRI 2.2. I also added a few non-critical currency updates as  #11.

**Comment by jnankin** [comment]
Thanks nerab!  I added TravisCI and verified that the gem works with MRI 2.2.
